### ISSUE TITLE
Disappeared from melpa

### ISSUE THREAD

**Issue by pronobis** [flycheck/flycheck-google-cpplint#10]
It seems that flycheck-google-cpplint disappeared from MELPA. Is there any particular reason?

**Comment by zhanxw** [comment]
Lack of maintainer? 
https://github.com/melpa/melpa/pull/4379

**Comment by pronobis** [comment]
Is there really no maintainer? @lunaryorn?

**Comment by lunaryorn** [comment]
I dropped out of Emacs months ago and do not not know what the current state of this package is.

**Comment by gjstein** [comment]
@lunaryorn I had been using an older of this package (obtained via MELPA) and it appears to still be working on my machines (running Emacs 24.5.1 and 25.1.1), despite being rather old at this point.

**Comment by lunaryorn** [comment]
I'm sorry but I'm not the person to discuss this with. As I said I ended my involvement with Emacs months ago and feel no longer responsible for this package.

**Comment by gjstein** [comment]
Ah sorry to hear that. 

That said, however, if you're looking for someone to take over as maintaner, I'd be up to the task. It's not a particularly complicated package, and it would be a shame to see it permanently absent from MELPA.

**Comment by lunaryorn** [comment]
@gjstein I'm sorry but I just don't care anymore.  If you'd like to take over feel free to fork and sort things out with MELPA, or ask @cpitclaudel (who now maintains Flycheck afaik) to give you push access.

But please, don't mention me anymore.  I can't help you.

**Comment by jcs090218** [comment]
@cpitclaudel Is there anyone maintaining this package? I would like to take over maintenance of this package. ;)

If possible. I would also like to help maintain [flycheck-pos-tip](https://github.com/flycheck/flycheck-pos-tip) and [flycheck-popup-tip](https://github.com/flycheck/flycheck-popup-tip). These packages are kind of important to my daily workflow. Thanks!

**Comment by jcs090218** [comment]
@cpitclaudel Friendly ping here. :)

**Comment by jcs090218** [comment]
@lunaryorn Sorry for mentioning you. I wonder do you have the permission to give me the access for this repository? I am not getting any response from current maintainers. 😕

**Comment by cpitclaudel** [comment]
Sorry, it's taken me a while to work through email backlog.  I saw your message.  
We'd be happy to hand over maintenance to you, but for obvious security reasons we need to have a bit of a track record before handing commit rights.
Is there a feature that you would like in flycheck+cpplint?  Could you make a pull request for that?  Or do you have ideas to solve the open issues?

**Comment by jcs090218** [comment]
> Sorry, it's taken me a while to work through email backlog. I saw your message.

No worries! :)

> We'd be happy to hand over maintenance to you, but for obvious security reasons we need to have a bit of a track record before handing commit rights.
Is there a feature that you would like in flycheck+cpplint? Could you make a pull request for that? Or do you have ideas to solve the open issues?

Ah.. Not on top of my head now. I think the first step would be re-submit back to melpa? I am not trying to make big changes to this repository, probably doing some simple stuffs (answer question, review PR, etc). I am just trying to keep good package alive. :)

**Comment by cpitclaudel** [comment]
Sounds good.  If you commit to responding to bug reports and reviewing PRs (starting with the issues that are currently open), I'm OK with putting the package back on MELPA :)  Can you take care of that process?  Thanks!

**Comment by jcs090218** [comment]
> Sounds good. If you commit to responding to bug reports and reviewing PRs (starting with the issues that are currently open), I'm OK with putting the package back on MELPA :) Can you take care of that process? Thanks!

Sounds good! Thank you! :)

---

@cpitclaudel Seeing you have time to response. Allow me to brought up another issue here https://github.com/jcs-elpa/flycheck-grammarly/issues/6. Thanks!

**Comment by jcs090218** [comment]
I think this can be close for now! :)

**Comment by jcs090218** [comment]
Ah, reopen this and wait until I have resubmit to MELPA!

**Comment by jcs090218** [comment]
This is back to melpa! See https://melpa.org/#/flycheck-google-cpplint.

Close this now! :)
