### ISSUE TITLE
suggesting install instructions for cpplint from pypi

### ISSUE THREAD

**Issue by tkruse** [flycheck/flycheck-google-cpplint#3]
Hi,
I maintain a version of cpploint on pypi:
https://github.com/tkruse/cpplint

While it is not always up-to-date, it is easier and cleaner to install / uninstall:

```
$ sudo pip install cpplint
```

Maybe you'd like to consider that in your readme.

**Comment by jcs090218** [comment]
I agree with you. I have tried with the latest installation guide but not working on Windows.
